name: pieno
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  lottie: ^3.1.2
  json_annotation: ^4.9.0
  build_runner: ^2.4.11
  liquid_progress_indicator_v2: ^0.5.0
  syncfusion_flutter_charts: ^26.1.38 
  flutter_native_splash: ^2.4.0
  dio: ^5.5.0
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2
  location: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: futura
      fonts:
        - asset: fonts/futura/FuturaPTCondMedium.otf
        - asset: fonts/futura/FuturaPTCondMediumOblique.otf
          style: italic
        - asset: fonts/futura/FuturaPTBold.otf
          weight: 700
